### ISSUE TITLE
Installation failing when running project from VS

### ISSUE THREAD

**Issue by mikeprag** [Appleseed/portal#17]
Hi,
I'm very interested in reviewing your framework (It looks really good). I have downloaded the VS project and built it with no issues. I have run the wizard which looks like it creates the DB and all Stored Procedures but then fails with the exception below. Any ideas?

Thanks

Mike

   at Appleseed.Framework.Settings.Database.GetDatabaseVersion() in C:\Development\TestProjects\portal-1.1.0.0\Master\Appleseed\Projects\Appleseed.Framework.Core\DAL\Database.cs:line 77
   at Appleseed.Framework.Settings.Database.get_DatabaseVersion() in C:\Development\TestProjects\portal-1.1.0.0\Master\Appleseed\Projects\Appleseed.Framework.Core\DAL\Database.cs:line 40
   at Appleseed.Framework.Update.Services.get_DatabaseVersion() in C:\Development\TestProjects\portal-1.1.0.0\Master\Appleseed\Projects\Appleseed.Framework.Core\Update\Services.cs:line 56
   at Appleseed.Framework.Update.Services.RunDBUpdate(String connectionString) in C:\Development\TestProjects\portal-1.1.0.0\Master\Appleseed\Projects\Appleseed.Framework.Core\Update\Services.cs:line 330
   at Appleseed.Global.UpdateDB() in C:\Development\TestProjects\portal-1.1.0.0\Master\Appleseed\WebSites\Appleseed\Global.asax.cs:line 405
   at Appleseed.Global.CheckAndUpdateDB(HttpContext context, String requestPath) in C:\Development\TestProjects\portal-1.1.0.0\Master\Appleseed\WebSites\Appleseed\Global.asax.cs:line 382
   at Appleseed.Global.AppleseedApplication_BeginRequest(Object sender, EventArgs e) in C:\Development\TestProjects\portal-1.1.0.0\Master\Appleseed\WebSites\Appleseed\Global.asax.cs:line 248
   at Appleseed.Global.Application_BeginRequest(Object sender, EventArgs e) in C:\Development\TestProjects\portal-1.1.0.0\Master\Appleseed\WebSites\Appleseed\Global.asax.cs:line 431
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by ramseur** [comment]
Hi Mike,

Make sure you have the .NET 4.6.1 framework installed.  Simply .NET 4.6 will not work.

The installer will come up and install fine on 4.6 but the portal needs 4.6.1 to run.

Also you can post me your \rb_logs\rb_logs.resx file at the bottom so I can see if there is any error there.

**Comment by ramseur** [comment]
Hey Mike, I dont know if you got the portal to install.

You can try using the Portal Stack that will configure the components for you and has 4.6.1 installed : https://github.com/Appleseed/portal-stack

**Comment by mikeprag** [comment]
Hi Eric,

Thanks, I got it to compile and run through VS on another laptop (I'll go
back and check the other laptop this week). The framework looks very
interesting however the page load times seem exceptionally long? It takes a
full minute to load up the first page and each subsequent page (including
the admin interface) takes 20 - 30 secs. Is this something that I am doing
wrong? In VS, web.config continually seems to be being updated and so I do
not know if this has an effect in restarting the app?

Also, do you have any other examples /samples that show more involved
functionality?

Thanks in advance

Mike

**Comment by ramseur** [comment]
Hey Mike,

I am pleased you got the portal to come up.

We are currently reworking the SQL and Initial load time functions in the next version 1.2.   

I would recommend you not run the portal through Visual Studio if you are not developing on it.  You should use a release build ( either created by yourself or from the releases page).  Also host this release build in IIS and not in Visual Studio Cassani.

I will create another issue on Web.config modifications.   For now, you can make your web.config read only to your Application Pool Idenity AFTER install so that it never writes to it again.  I will close this issue as it was reported for the portal failing to install and it seems you have resolved that issue. 

The link below will provide you with examples of Appleseed Functionality 

http://learn.appleseedapp.net/en/latest/docs/portal/

Regards,
Eric
